### ISSUE TITLE
Após marcar o bot, as vezes é recebido dois replies, sendo um deles um tweet diferente, que não é do usuário

### ISSUE THREAD

**Issue by JoaoMagal** [CaioMadeira/The-Philosopher-BOT#1]
**DETALHES DO BUG**
Após marcar o bot, há uma chance de que um reply de outro usuário possa ser recebido.
Ocorreu algumas vezes comigo, mas não parece ser constante; Acabou de acontecer comigo quando eu usei o bot de maneira errada.

**PASSOS PARA REPLICAR**
1. Marcar bot com uma mensagem
2. Verificar notificações.

**IMAGENS/GIFS**
![Screenshot from 2020-08-21 14-34-51](https://user-images.githubusercontent.com/27467821/90918711-8e0fa180-e3bb-11ea-9b7a-be3479aa6508.png)

![Peek 2020-08-21 14-40](https://user-images.githubusercontent.com/27467821/90919168-5523fc80-e3bc-11ea-9bb5-ed50e46c8d00.gif)

**Comment by JoaoMagal** [comment]
Não sei se é um bug também (pode ser só que vocês tiraram a feature), mas não tem mais como comentar só `#philobot` no post e a imagem ser gerada a partir do post?

**Comment by caiomadeira** [comment]
Opa, a gente meio que só viu isso hoje. A gente notou isso recentemente, mas obrigado. Vamos atribuir o seu devido credito!
